urls.py
from django.urls import path
from . import views
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('', views.play, name='picsna-home'),
    path('play/', views.play, name='picsna-play'),
    path('addImg/', views.addImg, name='picsna-addImg'),
    path('detail/<int:detail_id>/', views.detail, name='picsna-detail'),

    path('../users/register/', user_views.register, name='users-register'),
    path('../users/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('../users/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    
]

models.py
from django.db import models
from django.contrib.auth.models import User

class DetailV(models.Model):
	picture 	= models.ImageField(upload_to='picsna/static/images/detail_view', blank=False)
	author 		= models.ForeignKey(User, on_delete = models.DO_NOTHING)
	title 		= models.CharField( max_length = 100 )
	link 		= models.CharField( max_length = 250 )
	date_added 	= models.DateTimeField('date added', auto_now_add=True)

	def __str__(self):
		return self.title

class Comment(models.Model):
	detail 		= models.ForeignKey(DetailV, on_delete=models.CASCADE, related_name='comments')
	author 		= models.ForeignKey(User, on_delete = models.DO_NOTHING)
	content 	= models.TextField()
	date_added 	= models.DateTimeField('date snaped', auto_now_add=True)

forms.py
# from django.core.files.uploadedfile import SimpleUploadedFile
from django.forms import ModelForm
from .models import Comment
from .models import DetailV

class AddImg(ModelForm):
	class Meta:
		model = DetailV
		fields = ['picture','title', 'link', 'author']

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['detail', 'author', 'content']
		

views.py
from django.shortcuts import render, redirect
from django.core.files.uploadedfile import SimpleUploadedFile
from .models import Comment
from .models import DetailV
from .forms import AddImg
from .forms import CommentForm
from PIL import Image

# is_checked = IntVar()

def play(request):
	context = {
		'detailViews': DetailV.objects.all(),
		'title': 'Play',
		'user': request.user,
	}
	
	return render(request, 'picsna/play.html', context)

def addImg(request):

	if request.method == 'POST':
		form = AddImg(request.POST, request.FILES) 
		if form.is_valid():
			form.save()			
		else:
			print("Invalid Form")	

		return redirect('picsna-play')		
	else:
		form = AddImg();

	return render(request, 'picsna/addImg.html', {'form' : form })

def detail(request, detail_id):

	# FORM MANIPULATION FOR COMMENT
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			form.save()			
		else:
			print("Invalid Form")	
	
	form = CommentForm(initial={'detail': DetailV.objects.get(id=detail_id)})

	context = {
		'title': 'Detail',
		'detail': DetailV.objects.get(id=detail_id),
		'comments': Comment.objects.filter(detail=detail_id),
		'user': request.user,
		'form': form,
	}

	return render(request, 'picsna/detail.html', context)

templates/picsna/addImg.html
{% extends "picsna/base.html" %}
{% block content %}
	
  <div class="addImg">
  {% if user.is_authenticated %}
    
    <form enctype="multipart/form-data" method="POST" id="add-form" name="form" >  
    
      {% csrf_token %}
      <fieldset id="add-fieldset" class="form-group">
          {{form.errors}}
        <div class="picture field">
          <label for="id_author">Author:</label>
          {{ form.author }}
        </div>
        <div class="picture field">
          <label for="id_picture">Picture:</label>
          {{ form.picture }}
        </div>
        <div class="title field">
          <label for="id_title">Title:</label>
          {{ form.title }}
        </div>
        <div class="link field">
          <label for="id_link">Link:</label>
          {{ form.link }}
        </div>
      </fieldset>
    
      
      <a id="back" href="{% url 'picsna-play' %}">BACK</a>
      <button type="submit" id="submit">SUBMIT</button>
      
    </form>

  {% else %}

	<div class="failure">
		<h3>You have no permission to add new content.</h3>
		<p>please <a href="{% url 'users-login' %}">Login</a> or <a href="{% url 'users-register' %}">Register</a> to proceed.</p>
	</div>

  {% endif %}
  </div>
{% endblock content %}

templates/picsna/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    
    {% if title %}
      <title>Picsna - {{ title }}</title>
    {% else %}
      <title>Picsna</title>
    {% endif %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'stylesheets/screen.css' %}">
  </head>
  <body>
    <div class="app">
    
        {% block content %}
        {% endblock %}
  
    </div>
  </body>
</html>

templates/picsna/detail.html
{% extends "picsna/base.html" %}
{% block content %}
	
  <div class="detail">
    
    <div class="preview">

      <img class="detail-img" src="../../../{{ detail.picture.url|cut:"picsna/" }}" alt="{{ detail.title }}">  

    </div>

    <div class="comments">
    
      {% for comment in comments %}
      
        <div class="comment">
          <span class="user">
            {{comment.author}}
          </span>
          <p>
            {{comment.content}}
          </p>

        </div>

      {% endfor %}

    </div>


  {% if user.is_authenticated %}
    <form enctype="multipart/form-data" method="POST" id="comment-form" name="form" >  
    
      {% csrf_token %}
      <fieldset id="comment-fieldset" class="form-group">
        {{form.errors}}

        <div class="detail-field">
          <label for="id_detail">Detail:</label>
          {{ form.detail }}
        </div>
        <div class="author-field">
          <label for="id_author">Author:</label>
          {{ form.author }}
        </div>
        <div class="comment-field">
          <label for="id_comment">Comment:</label>
          {{ form.content }}
        </div>

      </fieldset>
    
      <a id="back" href="{% url 'picsna-play' %}">BACK</a>
      <button type="submit" id="submit">Add comment</button>
      
    </form>

  {% else %}

	<div class="failure">
		<h3>You have no permission</h3>
		<p>please <a href="{% url 'users-login' %}">Login</a> or <a href="{% url 'users-register' %}">Register</a> to proceed.</p>
	</div>

  {% endif %}
  </div>
{% endblock content %}

templates/picsna/play.html
{% extends "picsna/base.html" %}
{% block content %}

  <div class="play">
  	<div class="play-toolbar">
  	{% if user.is_authenticated %}
		<a href="{% url 'users-logout' %}">Log out</a>
		<a href="{% url 'picsna-addImg' %}">Add Image</a>
  	{% else %}
		<a href="{% url 'users-login' %}">Login</a>
		<a href="{% url 'users-register' %}">Register</a>
	{% endif %}
	{% if user.is_staff %}
		<button id='remove' type='submit' href="{% url 'picsna-addImg' %}">Remove Image</a>
	{% endif %}

	</div>

    {% for detail in detailViews %}
    	<div class="detail-item">
			<a href="{% url 'picsna-detail' detail.id %}"><img class="detail-img" src="../../{{ detail.picture.url|cut:"picsna/" }}" alt="{{ detail.title }}"></a>
			
			{% if user.is_staff %}
			<label class="container">Remove 
				<input type="checkbox" name="remove" class="checkbox">
				<span class="checkmark"></span>
			</label>
			{% endif %}		

	      <div class="detail-description">
	        <h1>{{ detail.title }}</h1>
	        <p>By {{ detail.author }} on {{ detail.date_added|date:"F d, Y" }}</p>
	        <a href='{{ detail.link }}'>LINK</a>
	      </div>
	  </div>
    {% endfor %}

  </div>
{% endblock content %}